config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :users, :projects, :tasks

  get "/tasks/new/:p_id" => 'tasks#new'

  get "/login" => 'session#new', :as => 'login'
  post "/login" => 'session#create'
  delete "/logout" => 'session#destroy', :as => 'logout'


end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :text
#  description :text
#  private     :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :tasks
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  title       :text
#  description :text
#  complete    :boolean          default(FALSE)
#  project_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Task < ActiveRecord::Base
  belongs_to :project
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :text
#  email           :text
#  password_digest :text
#  image           :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  has_secure_password
  has_and_belongs_to_many :projects
  has_many :tasks, :through => :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :fetch_user
  

  private
    def fetch_user
      @current_user = User.find_by( :id => session[:user_id] )
      session[:user_id] = nil unless @current_user
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate, :only => [:index]

  def index
  end

  def new
    @project = Project.new
    @users = User.all
  end

  def create
    project = Project.new project_params
    project.users << @current_user
    project.save

    params[:project][:user_ids].shift
    user_ids = params[:project][:user_ids]

    user_ids.each do |u|
      x = User.find u
      project.users << x unless project.users.include? x
    end

    redirect_to projects_path
  end

  def show
    @project = Project.find params[:id]
    @users = User.all
  end

  def edit
    @project = Project.find params[:id]
    @users = User.all
  end

  def update
    project = Project.find params[:id]
    project.update project_params
    project.save

    project.users.delete_all
    project.users << @current_user
    params[:project][:user_ids].shift
    user_ids = params[:project][:user_ids]
    user_ids.each do |u|
      x = User.find u
      project.users << x unless project.users.include? x
    end

    redirect_to project_path
  end

  def destroy
    project = Project.find params[:id]
    project.destroy

    redirect_to projects_path
  end

  private
    def authenticate
      redirect_to login_path unless @current_user
    end

    def project_params
      params.require(:project).permit(:title, :description, :user_ids)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :authenticate, :only => [:new]

  def new
    #direct to login screen (new.html.erb)
  end

  def create
    #Process the login form
    user = User.find_by :email => params[:email]

    if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in"
      redirect_to user
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def destroy
    #Destroy session detail
    session[:user_id] = nil
    flash[:success] = "Successfully logged out"
    redirect_to login_path
  end

  private
    def authenticate
      redirect_to users_path if @current_user
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
    @cur_project = Project.find params[:p_id]
  end

  def create
    task = Task.new task_params
    task.save

    redirect_to project_path(task_params[:project_id])
  end

  def edit
    @task = Task.find params[:id]
  end

  def update
    task = Task.find params[:id]
    task.update task_params

    redirect_to project_path(task_params[:project_id])
  end

  def destroy
    task = Task.find params[:id]
    task.destroy

    redirect_to :back
  end

  private
    def task_params
      params.require(:task).permit(:title, :description, :project_id, :complete)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @user.save

    session[:user_id] = @user.id
    @current_user = @user
    flash[:success] = "Now logged in as #{@current_user.username}"

    redirect_to users_path
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user = User.find params[:id]
    if user.update user_params
      flash[:success] = "Details have been updated"
    else
      flash[:error] = "Password error, details unchanged"
    end

    redirect_to user
  end

  def destroy
    user = User.find params[:id]
    user.destroy

    redirect_to new_user_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :image, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tick It</title>
  <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class="top_nav_bar">
      <div class="title_img"><img src="http://i.imgur.com/3CSqyT5.png"> </div>
      <div class="title">Tick It
        <% if !@current_user %>
          <span><i>"Your TICKET to success"</i> -Small Jess</span>
        <% else %>
          <span>Currently logged in as: <%= @current_user.username %> (<%= link_to "logout", logout_path, :method => :delete %>)</span>
        <% end %>
      </div>
      <div class="nav_list">
        <nav>
          <ul>
            <% if @current_user %>
              <li><a href="<%= "/users/#{@current_user.id}" %>" class="nav_butt">Profile</a></li>
              <li><a href="<%= projects_path %>" class="nav_butt">Projects</a></li>
              <li><a href="<%= new_project_path %>" class="nav_butt">New Project</a></li>

            <% else %>
              <li><a href= "<%= login_path %>" class="nav_butt">Login</a></li>
              <li><a href="<%= new_user_path %>" class="nav_butt">Sign Up</a></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div class="hero_container">
  <div class="hero_content">
    <h2>Tick It provides a simple solution for teams to track tasks across multiple projects.</h2>
  </div>
  <br>
  <br>
  <a href="/users/new">
    <div class="CTA">
      <span>Get Started!</span>
    </div>
  </a>
</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description, size: "24x6", :required => true %>
  </p>
  <p>Select project members</p>
  <p>
    <% user_arr = [] %>
    <% @users.each do |u| %>
      <% x = [u.username, u.id] %>
      <% user_arr.push x %>
    <% end %>
    <%= f.select( :user_ids, user_arr, {}, {:multiple => true}) %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<div class="projects_container">
  <% @current_user.projects.each do |p| %>
    <div class="project_display">
      <h3><%= link_to p.title, p %></h3>
      <p><%= p.description %></p>
      <p>
        Tasks:
        <% p.tasks.each do |t| %>
          <% if t.complete %>
            <div class="task_container_done">
              <%= t.title %><img src="http://i.imgur.com/3CSqyT5.png">
            </div>
          <% else %>
            <div class="task_container"><%= t.title %></div>
          <% end %>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<div class="project_show">
  <h2><%= @project.title %></h2>

  <p><%= @project.description %></p>

  <p>
    Tasks:
    <% @project.tasks.each do |t| %>
      <% if t.complete %>
        <div class="task_container_show_done">
      <% else %>
        <div class="task_container_show">
      <% end %>
        <h3><%= t.title %></h3> <br> <%= t.description %>
        <br>
        <span><%= link_to "Edit", "/tasks/#{t.id}/edit" %>  |  <%= link_to "Delete", "/tasks/#{t.id}", :method => :delete, :data => { :confirm => 'Are you sure you want to delete this task?' } %></span>
      </div>
    <% end %>
      <%= link_to "Add task", "/tasks/new/#{@project.id}" %>
  </p>

  <p>
    Members:
    <br>
      <% @project.users.each do |u| %>
        <%= link_to u.username, user_path(u) %>
        <br>
      <% end %>
  </p>

  <%= link_to "Edit project", edit_project_path %>
  <%= link_to "Delete project", project_path, :method => :delete, :data => { :confirm => "Are you sure you want to delete: #{@project.title}?" } %>
</div>

app/views/session/new.html.erb
<div class="hero_container">

  <%= form_tag login_path do %>
    <p>
      <%= label_tag :email %>
      <%= email_field_tag :email %>
    </p>

    <p>
      <%= label_tag :password %>
      <%= password_field_tag :password %>
    </p>

    <%= submit_tag "Login" %>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>
  </p>
  <p>
    <%= f.label :description %>
  </p>
    <%= f.text_area :description, size: "24x6", :required => true %>
  <p>
    <!-- <% projects_arr = [] %>
    <% @current_user.projects.each do |p| %>
      <% x = [p.title, p.id] %>
      <% projects_arr.push x %>
    <% end %> -->
  </p>
    <%= f.number_field :project_id, :value => @cur_project.id  %>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<div class="hero_container">
  <h2>Edit Task</h2>

  <%= form_for @task do |f| %>

    <p>
      <%= f.label :title %>
      <%= f.text_field :title, :required => true %>
    </p>

    <p>
      <%= f.label :description %>
    </p>

    <p>
      <%= f.text_area :description, size: "24x6", :required => true %>
    </p>

    <p>
      <%= f.label :complete %>
      <%= f.check_box :complete, :required => false %>
    </p>

      <%= f.number_field :project_id, :required => true %>

      <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="hero_container">
  <h2>New Task for: <%= @cur_project.title %></h2>

  <%= render :partial => 'form' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username, :required => true %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email, :required => true %>
  </p>
  <p>
    <%= f.label :image %>
    <%= f.text_field :image%>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password, :required => true %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required => true %>
  </p>

  <%= f.submit "Submit" %>
<% end %>

app/views/users/edit.html.erb
<div class="hero_container">
  <h2>Edit Profile</h2>

  <%= render :partial => 'form' %>
</div>

app/views/users/index.html.erb
<div class="hero_container">
  <h2>All Users</h2>

  <% @users.each do |u| %>
    <ul>
      <li>Username: <%= link_to(u.username, user_path(u))%></li>
      <li>Email: <%= u.email %></li>
      <li>Password Digest: <%= u.password_digest %></li>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="hero_container">
  <%= render :partial => 'form' %>
</div>

app/views/users/show.html.erb
<div class="hero_container">
  <h2>User profile</h2>

  <% if flash[:success] %>
    <p><%= flash[:success] %></p>
  <% end %>

  <% if flash[:error] %>
    <p><%= flash[:error] %></p>
  <% end %>

  <h4><%= @user.username %></h4>
  <img src="<%= @user.image %>">
  <p><%= @user.email %></p>
  <p>
    <%= link_to( "Edit profile", edit_user_path(@user) ) %>
  </p>
  <p>
    <%= link_to( "Delete account", user_path(@user), :method => :delete ) %>
  </p>
</div>